### ISSUE TITLE
I made a browser-based search for fimfarchive

### ISSUE THREAD

**Issue by a0346f102085fe9f** [JockeTF/fimfarchive#5]
Hello!

I wanted to let you know that I made a browser-based search for fimfarchive. It's not a full-text search, but it is content-based. It relies on text embeddings produced by the SPLADE v2 neural network.

You can find it at https://a0346f102085fe9f.github.io/IAS2/

It can be hosted locally too.

You can add it to the "third party projects" of the fimfarchive page on fimfiction if you see fit.

**Comment by JockeTF** [comment]
Hey, thanks! That's pretty cool! I added it to the user page. Give me a poke if you want it changed somehow.

Sorry about the late response, for whatever reason I didn't see the notification.
